dist: bionic
language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - vendor

before_install:
  - sudo apt-get update > /dev/null

install:
  - composer install
